# Common pipeline with build artifact and pre-push scanning
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      port:
        required: true
        type: string

env:
  APP_NAME: "nextjs-ts-app"
  DOCKER_REGISTRY: "docker.io"
  TRIVY_SEVERITY: "HIGH,CRITICAL"
  TRIVY_IGNORE_UNFIXED: "true"
  TRIVY_VULN_TYPE: "os,library"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag
        id: tag
        run: |
          echo "tag=$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      full_image_tag: ${{ steps.set_outputs.outputs.full_image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Set image outputs
        id: set_outputs
        run: |
          FULL_TAG="${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ needs.setup.outputs.image_tag }}"
          echo "full_image_tag=${FULL_TAG}" >> $GITHUB_OUTPUT
          echo "Building image: ${FULL_TAG}"
          
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.set_outputs.outputs.full_image_tag }}
          outputs: type=docker,dest=/tmp/image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image.tar
          retention-days: 1

  # trivy_scan:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}
  #   steps:
  #     - name: Download image artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: docker-image
          
  #     - name: Load Docker image
  #       run: |
  #         docker load -i image.tar
  #         echo "Loaded image: ${{ needs.build.outputs.image_name }}"
          
  #     - name: Run Trivy scan
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: ${{ needs.build.outputs.image_name }}
  #         format: 'table'
  #         exit-code: '1'
  #         severity: ${{ env.TRIVY_SEVERITY }}
  #         ignore-unfixed: ${{ env.TRIVY_IGNORE_UNFIXED }}
  #         vuln-type: ${{ env.TRIVY_VULN_TYPE }}

  push:
    needs: [setup, build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
          
      - name: Load Docker image
        run: |
          docker load -i /tmp/image.tar
          echo "Loaded image: ${{ needs.build.outputs.full_image_tag }}"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Push Docker image
        run: |

          FULL_IMAGE_TAG="${{ needs.setup.outputs.full_image_tag }}"
          # Verify image exists
          if ! docker inspect "${FULL_IMAGE_TAG}" >/dev/null 2>&1; then
            echo "::error::Image not found in local registry: ${FULL_IMAGE_TAG}"
            echo "Available images:"
            docker images
            exit 1
          fi

          # Push versioned tag
          VERSIONED_IMAGE="${{ needs.setup.outputs.full_image_tag }}"
          echo "Pushing versioned image: ${VERSIONED_IMAGE}"
          docker push "${VERSIONED_IMAGE}"
          
          # Push environment-specific latest tag
          ENV_LATEST_TAG="${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:latest-${{ github.event.inputs.environment }}"
          docker tag "${VERSIONED_IMAGE}" "${ENV_LATEST_TAG}"
          echo "Pushing environment latest: ${ENV_LATEST_TAG}"
          docker push "${ENV_LATEST_TAG}"

  deploy:
    needs: push
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_KEY }}
          known_hosts: unnecessary
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no \
              root@${{ secrets.DROPLET_IP }} \
              "docker pull ${{ needs.build.outputs.image_name }} && \
               docker stop ${{ env.APP_NAME }}-${{ inputs.environment }} || true && \
               docker rm ${{ env.APP_NAME }}-${{ inputs.environment }} || true && \
               docker run -d \
                 --name ${{ env.APP_NAME }}-${{ inputs.environment }} \
                 -p ${{ inputs.port }}:3000 \
                 -e NODE_ENV=${{ inputs.environment }} \
                 --restart unless-stopped \
                 ${{ needs.build.outputs.image_name }}"
