name: Deploy to Development Environment

on:
  push:
    branches:
      - develop
      - feature/add_github_actions_for_digitalocean

jobs:
  call-common-pipeline:
    uses: ./.github/workflows/common_pipeline.yml
    secrets: inherit
    with:
      environment: "development"
      port: "3000"
