name: Deploy to Development Environment

on:
  push:
    branches:
      - develop
      - feature/add_github_actions_for_digitalocean

jobs:
  call-common-pipeline:
    uses: ./.github/workflows/common_pipeline.yml
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read
    secrets: inherit
    with:
      environment: "development"
      port: "3000"
      runner: ubuntu-latest
