name: Deploy to Production Environment

on:
  push:
    branches: main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-common-pipeline:
    uses: ./.github/workflows/common_pipeline.yml
    secrets: inherit
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read
    with:
      environment: "production"
      port: "3001"
      runner: ubuntu-latest
